---
- name: Run prerequisite setup
  ansible.builtin.import_tasks: prereqs.yml

- name: Build container images
  ansible.builtin.import_tasks: images.yml

- name: Create podman secrets
  ansible.builtin.import_tasks: secrets.yml

- name: Deploy fleet-manager container
  ansible.builtin.import_tasks: deploy.yml

- name: Verify deployment
  ansible.builtin.import_tasks: verify.yml
